### PR TITLE
Styling changes

### PR DESCRIPTION
**Pull request by eambutu**
Hey Jack,

Love what you're doing! I spent 30 minutes or so doing some styling touchups on the website. I'm not sure exactly what look you want for the website, but thought that at least some of the changes (like the spacings) are not super controversial. LMK what you think, and how I can change it to better fit what you'd want for the website :)

Screenshot Desktop 1:
image
Screenshot Desktop 2:
image

Screenshots on Mobile (iPhone 6/7/8) 1:
image
Screenshots on Mobile (iPhone 6/7/8) 2:
image

### CODE REVIEW

**Comment by JackKelly** [comment]
This is *awesome*!  Thank you so much!  Open Climate Fix's first ever pull-request!  Very exciting!

Please can I just check: Do you know what the licensing terms are for the banner image?

**Comment by eambutu** [comment]
Good point. I found the image on Google images, can't really find anything about the license: https://www.alabamawx.com/?p=179274.

**Comment by JackKelly** [comment]
Thanks for checking!  If we don't know the licensing agreement then, unfortunately, we can't use the image.  Please could you either completely remove the image (and make the header text black) or find an alternative image on somewhere like Wikimedia Commons?  Thanks so much for doing this!  Your new style looks much better :)

**Comment by eambutu** [comment]
Removed the banner for now! Kept in the CSS to easily add in a banner, because I found some high quality images for like $12, that we can look into later.

**Comment by JackKelly** [comment]
Fantastic, thank you! I've merged your changes :)  Thanks again!

**Pull request merged**
